include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ### Error rules
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    ### Error rules

    ### Style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_private_typedef_functions: true
    avoid_shadowing_type_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    directives_ordering: true
    eol_at_end_of_file: true
    lines_longer_than_80_chars: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    one_member_abstracts: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true
    ### Style rules
